services:
- type: web
  name: next-js
  env: node
  plan: starter
  buildCommand: cd dir; yarn; yarn build
  startCommand: cd dir; date; yarn start
  afterFirstDeployCommand: echo hello; date; false
  pullRequestPreviewsEnabled: true
# Uncomment the following to deploy this app as a static site on render
# - type: web
#   name: nextjs-static
#   env: static
#   buildCommand: yarn; yarn build; yarn next export
#   staticPublishPath: out
#   pullRequestPreviewsEnabled: true     # optional

